version: '2'
services:

  test-game:
    container_name: "test-game"
    build: client
    ports:
      - 1337:80

  prometheus:
    container_name: "prometheus"
    build: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus/
  
  grafana:
    container_name: "grafana"
    build: grafana
    env_file:
      - ./grafana/.env.dev
    environment:
      - PROMETHEUS_URL=prometheus:9090
    ports:
      - 3000:3000
    volumes:
      - ./grafana/persist:/grafana-storage
      - ./grafana/provisioning:/etc/grafana/provisioning/
    depends_on:
      - prometheus