
@API=http://localhost:3000/graphql
@GAME_ID={{start.response.body.data.startGame.id}}

###

GET {{API}}?sdl

###
# @name start

POST {{API}}
X-REQUEST-TYPE: GraphQL

mutation {
    startGame {
      id
      facts
    }
}

###

POST {{API}}
X-REQUEST-TYPE: GraphQL

query {
    fetchGame(query: { gameId: "{{GAME_ID}}" }) {
        facts
    }
}
